INSERT INTO boletas (nombre, id_tipo_de_asiento, id_partido) VALUES
	('Boleta para primera ronda', 1, 1),
	('Boleta para primera ronda', 2, 1),
	('Boleta para primera ronda', 3, 1),
	('Boleta para primera ronda', 4, 1),
	('Boleta para primera ronda', 5, 1),
	('Boleta para primera ronda', 1, 2),
	('Boleta para primera ronda', 2, 2),
	('Boleta para primera ronda', 3, 2),
	('Boleta para primera ronda', 4, 2),
	('Boleta para primera ronda', 5, 2),
	('Boleta para primera ronda', 1, 3),
	('Boleta para primera ronda', 2, 3),
	('Boleta para primera ronda', 3, 3),
	('Boleta para primera ronda', 4, 3),
	('Boleta para primera ronda', 5, 3),
	('Boleta para primera ronda', 1, 4),
	('Boleta para primera ronda', 2, 4),
	('Boleta para primera ronda', 3, 4),
	('Boleta para primera ronda', 4, 4),
	('Boleta para primera ronda', 5, 4),
	('Boleta para primera ronda', 1, 5),
	('Boleta para primera ronda', 2, 5),
	('Boleta para primera ronda', 3, 5),
	('Boleta para primera ronda', 4, 5),
	('Boleta para primera ronda', 5, 5),
	('Boleta para primera ronda', 1, 6),
	('Boleta para primera ronda', 2, 6),
	('Boleta para primera ronda', 3, 6),
	('Boleta para primera ronda', 4, 6),
	('Boleta para primera ronda', 5, 6),
	('Boleta para primera ronda', 1, 7),
	('Boleta para primera ronda', 2, 7),
	('Boleta para primera ronda', 3, 7),
	('Boleta para primera ronda', 4, 7),
	('Boleta para primera ronda', 5, 7),
	('Boleta para primera ronda', 1, 8),
	('Boleta para primera ronda', 2, 8),
	('Boleta para primera ronda', 3, 8),
	('Boleta para primera ronda', 4, 8),
	('Boleta para primera ronda', 5, 8),
	('Boleta para primera ronda', 1, 9),
	('Boleta para primera ronda', 2, 9),
	('Boleta para primera ronda', 3, 9),
	('Boleta para primera ronda', 4, 9),
	('Boleta para primera ronda', 5, 9),
	('Boleta para primera ronda', 1, 10),
	('Boleta para primera ronda', 2, 10),
	('Boleta para primera ronda', 3, 10),
	('Boleta para primera ronda', 4, 10),
	('Boleta para primera ronda', 5, 10),
	('Boleta para primera ronda', 1, 11),
	('Boleta para primera ronda', 2, 11),
	('Boleta para primera ronda', 3, 11),
	('Boleta para primera ronda', 4, 11),
	('Boleta para primera ronda', 5, 11),
	('Boleta para primera ronda', 1, 12),
	('Boleta para primera ronda', 2, 12),
	('Boleta para primera ronda', 3, 12),
	('Boleta para primera ronda', 4, 12),
	('Boleta para primera ronda', 5, 12),
	('Boleta para primera ronda', 1, 13),
	('Boleta para primera ronda', 2, 13),
	('Boleta para primera ronda', 3, 13),
	('Boleta para primera ronda', 4, 13),
	('Boleta para primera ronda', 5, 13),
	('Boleta para primera ronda', 1, 14),
	('Boleta para primera ronda', 2, 14),
	('Boleta para primera ronda', 3, 14),
	('Boleta para primera ronda', 4, 14),
	('Boleta para primera ronda', 5, 14),
	('Boleta para primera ronda', 1, 15),
	('Boleta para primera ronda', 2, 15),
	('Boleta para primera ronda', 3, 15),
	('Boleta para primera ronda', 4, 15),
	('Boleta para primera ronda', 5, 15),
	('Boleta para primera ronda', 1, 16),
	('Boleta para primera ronda', 2, 16),
	('Boleta para primera ronda', 3, 16),
	('Boleta para primera ronda', 4, 16),
	('Boleta para primera ronda', 5, 16),
	('Boleta para primera ronda', 1, 32),
	('Boleta para primera ronda', 2, 32),
	('Boleta para primera ronda', 3, 32),
	('Boleta para primera ronda', 4, 32),
	('Boleta para primera ronda', 5, 32),
	('Boleta para primera ronda', 1, 33),
	('Boleta para primera ronda', 2, 33),
	('Boleta para primera ronda', 3, 33),
	('Boleta para primera ronda', 4, 33),
	('Boleta para primera ronda', 5, 33),
	('Boleta para primera ronda', 1, 34),
	('Boleta para primera ronda', 2, 34),
	('Boleta para primera ronda', 3, 34),
	('Boleta para primera ronda', 4, 34),
	('Boleta para primera ronda', 5, 34),
	('Boleta para primera ronda', 1, 35),
	('Boleta para primera ronda', 2, 35),
	('Boleta para primera ronda', 3, 35),
	('Boleta para primera ronda', 4, 35),
	('Boleta para primera ronda', 5, 35),
	('Boleta para primera ronda', 1, 36),
	('Boleta para primera ronda', 2, 36),
	('Boleta para primera ronda', 3, 36),
	('Boleta para primera ronda', 4, 36),
	('Boleta para primera ronda', 5, 36),
	('Boleta para primera ronda', 1, 37),
	('Boleta para primera ronda', 2, 37),
	('Boleta para primera ronda', 3, 37),
	('Boleta para primera ronda', 4, 37),
	('Boleta para primera ronda', 5, 37),
	('Boleta para primera ronda', 1, 38),
	('Boleta para primera ronda', 2, 38),
	('Boleta para primera ronda', 3, 38),
	('Boleta para primera ronda', 4, 38),
	('Boleta para primera ronda', 5, 38),
	('Boleta para primera ronda', 1, 39),
	('Boleta para primera ronda', 2, 39),
	('Boleta para primera ronda', 3, 39),
	('Boleta para primera ronda', 4, 39),
	('Boleta para primera ronda', 5, 39),
	('Boleta para primera ronda', 1, 47),
	('Boleta para primera ronda', 2, 47),
	('Boleta para primera ronda', 3, 47),
	('Boleta para primera ronda', 4, 47),
	('Boleta para primera ronda', 5, 47),
	('Boleta para primera ronda', 1, 48),
	('Boleta para primera ronda', 2, 48),
	('Boleta para primera ronda', 3, 48),
	('Boleta para primera ronda', 4, 48),
	('Boleta para primera ronda', 5, 48),
	('Boleta para primera ronda', 1, 49),
	('Boleta para primera ronda', 2, 49),
	('Boleta para primera ronda', 3, 49),
	('Boleta para primera ronda', 4, 49),
	('Boleta para primera ronda', 5, 49),
	('Boleta para primera ronda', 1, 50),
	('Boleta para primera ronda', 2, 50),
	('Boleta para primera ronda', 3, 50),
	('Boleta para primera ronda', 4, 50),
	('Boleta para primera ronda', 5, 50),
	('Boleta para primera ronda', 1, 51),
	('Boleta para primera ronda', 2, 51),
	('Boleta para primera ronda', 3, 51),
	('Boleta para primera ronda', 4, 51),
	('Boleta para primera ronda', 5, 51),
	('Boleta para primera ronda', 1, 52),
	('Boleta para primera ronda', 2, 52),
	('Boleta para primera ronda', 3, 52),
	('Boleta para primera ronda', 4, 52),
	('Boleta para primera ronda', 5, 52),
	('Boleta para primera ronda', 1, 53),
	('Boleta para primera ronda', 2, 53),
	('Boleta para primera ronda', 3, 53),
	('Boleta para primera ronda', 4, 53),
	('Boleta para primera ronda', 5, 53),
	('Boleta para primera ronda', 1, 54),
	('Boleta para primera ronda', 2, 54),
	('Boleta para primera ronda', 3, 54),
	('Boleta para primera ronda', 4, 54),
	('Boleta para primera ronda', 5, 54),
	('Boleta para primera ronda', 1, 55),
	('Boleta para primera ronda', 2, 55),
	('Boleta para primera ronda', 3, 55),
	('Boleta para primera ronda', 4, 55),
	('Boleta para primera ronda', 5, 55),
	('Boleta para primera ronda', 1, 56),
	('Boleta para primera ronda', 2, 56),
	('Boleta para primera ronda', 3, 56),
	('Boleta para primera ronda', 4, 56),
	('Boleta para primera ronda', 5, 56),
	('Boleta para primera ronda', 1, 57),
	('Boleta para primera ronda', 2, 57),
	('Boleta para primera ronda', 3, 57),
	('Boleta para primera ronda', 4, 57),
	('Boleta para primera ronda', 5, 57),
	('Boleta para primera ronda', 1, 58),
	('Boleta para primera ronda', 2, 58),
	('Boleta para primera ronda', 3, 58),
	('Boleta para primera ronda', 4, 58),
	('Boleta para primera ronda', 5, 58),
	('Boleta para primera ronda', 1, 59),
	('Boleta para primera ronda', 2, 59),
	('Boleta para primera ronda', 3, 59),
	('Boleta para primera ronda', 4, 59),
	('Boleta para primera ronda', 5, 59),
	('Boleta para primera ronda', 1, 60),
	('Boleta para primera ronda', 2, 60),
	('Boleta para primera ronda', 3, 60),
	('Boleta para primera ronda', 4, 60),
	('Boleta para primera ronda', 5, 60),
	('Boleta para primera ronda', 1, 61),
	('Boleta para primera ronda', 2, 61),
	('Boleta para primera ronda', 3, 61),
	('Boleta para primera ronda', 4, 61),
	('Boleta para primera ronda', 5, 61),
	('Boleta para primera ronda', 1, 62),
	('Boleta para primera ronda', 2, 62),
	('Boleta para primera ronda', 3, 62),
	('Boleta para primera ronda', 4, 62),
	('Boleta para primera ronda', 5, 62),
	('Boleta para primera ronda', 1, 78),
	('Boleta para primera ronda', 2, 78),
	('Boleta para primera ronda', 3, 78),
	('Boleta para primera ronda', 4, 78),
	('Boleta para primera ronda', 5, 78),
	('Boleta para primera ronda', 1, 79),
	('Boleta para primera ronda', 2, 79),
	('Boleta para primera ronda', 3, 79),
	('Boleta para primera ronda', 4, 79),
	('Boleta para primera ronda', 5, 79),
	('Boleta para primera ronda', 1, 80),
	('Boleta para primera ronda', 2, 80),
	('Boleta para primera ronda', 3, 80),
	('Boleta para primera ronda', 4, 80),
	('Boleta para primera ronda', 5, 80),
	('Boleta para primera ronda', 1, 81),
	('Boleta para primera ronda', 2, 81),
	('Boleta para primera ronda', 3, 81),
	('Boleta para primera ronda', 4, 81),
	('Boleta para primera ronda', 5, 81),
	('Boleta para primera ronda', 1, 82),
	('Boleta para primera ronda', 2, 82),
	('Boleta para primera ronda', 3, 82),
	('Boleta para primera ronda', 4, 82),
	('Boleta para primera ronda', 5, 82),
	('Boleta para primera ronda', 1, 83),
	('Boleta para primera ronda', 2, 83),
	('Boleta para primera ronda', 3, 83),
	('Boleta para primera ronda', 4, 83),
	('Boleta para primera ronda', 5, 83),
	('Boleta para primera ronda', 1, 84),
	('Boleta para primera ronda', 2, 84),
	('Boleta para primera ronda', 3, 84),
	('Boleta para primera ronda', 4, 84),
	('Boleta para primera ronda', 5, 84),
	('Boleta para primera ronda', 1, 85),
	('Boleta para primera ronda', 2, 85),
	('Boleta para primera ronda', 3, 85),
	('Boleta para primera ronda', 4, 85),
	('Boleta para primera ronda', 5, 85),
	('Boleta para primera ronda', 1, 93),
	('Boleta para primera ronda', 2, 93),
	('Boleta para primera ronda', 3, 93),
	('Boleta para primera ronda', 4, 93),
	('Boleta para primera ronda', 5, 93),
	('Boleta para primera ronda', 1, 94),
	('Boleta para primera ronda', 2, 94),
	('Boleta para primera ronda', 3, 94),
	('Boleta para primera ronda', 4, 94),
	('Boleta para primera ronda', 5, 94),
	('Boleta para primera ronda', 1, 95),
	('Boleta para primera ronda', 2, 95),
	('Boleta para primera ronda', 3, 95),
	('Boleta para primera ronda', 4, 95),
	('Boleta para primera ronda', 5, 95),
	('Boleta para primera ronda', 1, 96),
	('Boleta para primera ronda', 2, 96),
	('Boleta para primera ronda', 3, 96),
	('Boleta para primera ronda', 4, 96),
	('Boleta para primera ronda', 5, 96),
	('Boleta para primera ronda', 1, 97),
	('Boleta para primera ronda', 2, 97),
	('Boleta para primera ronda', 3, 97),
	('Boleta para primera ronda', 4, 97),
	('Boleta para primera ronda', 5, 97),
	('Boleta para primera ronda', 1, 98),
	('Boleta para primera ronda', 2, 98),
	('Boleta para primera ronda', 3, 98),
	('Boleta para primera ronda', 4, 98),
	('Boleta para primera ronda', 5, 98),
	('Boleta para primera ronda', 1, 99),
	('Boleta para primera ronda', 2, 99),
	('Boleta para primera ronda', 3, 99),
	('Boleta para primera ronda', 4, 99),
	('Boleta para primera ronda', 5, 99),
	('Boleta para primera ronda', 1, 100),
	('Boleta para primera ronda', 2, 100),
	('Boleta para primera ronda', 3, 100),
	('Boleta para primera ronda', 4, 100),
	('Boleta para primera ronda', 5, 100),
	('Boleta para primera ronda', 1, 101),
	('Boleta para primera ronda', 2, 101),
	('Boleta para primera ronda', 3, 101),
	('Boleta para primera ronda', 4, 101),
	('Boleta para primera ronda', 5, 101),
	('Boleta para primera ronda', 1, 102),
	('Boleta para primera ronda', 2, 102),
	('Boleta para primera ronda', 3, 102),
	('Boleta para primera ronda', 4, 102),
	('Boleta para primera ronda', 5, 102),
	('Boleta para primera ronda', 1, 103),
	('Boleta para primera ronda', 2, 103),
	('Boleta para primera ronda', 3, 103),
	('Boleta para primera ronda', 4, 103),
	('Boleta para primera ronda', 5, 103),
	('Boleta para primera ronda', 1, 104),
	('Boleta para primera ronda', 2, 104),
	('Boleta para primera ronda', 3, 104),
	('Boleta para primera ronda', 4, 104),
	('Boleta para primera ronda', 5, 104),
	('Boleta para primera ronda', 1, 105),
	('Boleta para primera ronda', 2, 105),
	('Boleta para primera ronda', 3, 105),
	('Boleta para primera ronda', 4, 105),
	('Boleta para primera ronda', 5, 105),
	('Boleta para primera ronda', 1, 106),
	('Boleta para primera ronda', 2, 106),
	('Boleta para primera ronda', 3, 106),
	('Boleta para primera ronda', 4, 106),
	('Boleta para primera ronda', 5, 106),
	('Boleta para primera ronda', 1, 107),
	('Boleta para primera ronda', 2, 107),
	('Boleta para primera ronda', 3, 107),
	('Boleta para primera ronda', 4, 107),
	('Boleta para primera ronda', 5, 107),
	('Boleta para primera ronda', 1, 108),
	('Boleta para primera ronda', 2, 108),
	('Boleta para primera ronda', 3, 108),
	('Boleta para primera ronda', 4, 108),
	('Boleta para primera ronda', 5, 108),
	('Boleta para primera ronda', 1, 124),
	('Boleta para primera ronda', 2, 124),
	('Boleta para primera ronda', 3, 124),
	('Boleta para primera ronda', 4, 124),
	('Boleta para primera ronda', 5, 124),
	('Boleta para primera ronda', 1, 125),
	('Boleta para primera ronda', 2, 125),
	('Boleta para primera ronda', 3, 125),
	('Boleta para primera ronda', 4, 125),
	('Boleta para primera ronda', 5, 125),
	('Boleta para primera ronda', 1, 126),
	('Boleta para primera ronda', 2, 126),
	('Boleta para primera ronda', 3, 126),
	('Boleta para primera ronda', 4, 126),
	('Boleta para primera ronda', 5, 126),
	('Boleta para primera ronda', 1, 127),
	('Boleta para primera ronda', 2, 127),
	('Boleta para primera ronda', 3, 127),
	('Boleta para primera ronda', 4, 127),
	('Boleta para primera ronda', 5, 127),
	('Boleta para primera ronda', 1, 128),
	('Boleta para primera ronda', 2, 128),
	('Boleta para primera ronda', 3, 128),
	('Boleta para primera ronda', 4, 128),
	('Boleta para primera ronda', 5, 128),
	('Boleta para primera ronda', 1, 129),
	('Boleta para primera ronda', 2, 129),
	('Boleta para primera ronda', 3, 129),
	('Boleta para primera ronda', 4, 129),
	('Boleta para primera ronda', 5, 129),
	('Boleta para primera ronda', 1, 130),
	('Boleta para primera ronda', 2, 130),
	('Boleta para primera ronda', 3, 130),
	('Boleta para primera ronda', 4, 130),
	('Boleta para primera ronda', 5, 130),
	('Boleta para primera ronda', 1, 131),
	('Boleta para primera ronda', 2, 131),
	('Boleta para primera ronda', 3, 131),
	('Boleta para primera ronda', 4, 131),
	('Boleta para primera ronda', 5, 131),
	('Boleta para primera ronda', 1, 132),
	('Boleta para primera ronda', 2, 132),
	('Boleta para primera ronda', 3, 132),
	('Boleta para primera ronda', 4, 132),
	('Boleta para primera ronda', 5, 132),
	('Boleta para primera ronda', 1, 133),
	('Boleta para primera ronda', 2, 133),
	('Boleta para primera ronda', 3, 133),
	('Boleta para primera ronda', 4, 133),
	('Boleta para primera ronda', 5, 133),
	('Boleta para primera ronda', 1, 134),
	('Boleta para primera ronda', 2, 134),
	('Boleta para primera ronda', 3, 134),
	('Boleta para primera ronda', 4, 134),
	('Boleta para primera ronda', 5, 134),
	('Boleta para primera ronda', 1, 135),
	('Boleta para primera ronda', 2, 135),
	('Boleta para primera ronda', 3, 135),
	('Boleta para primera ronda', 4, 135),
	('Boleta para primera ronda', 5, 135),
	('Boleta para primera ronda', 1, 136),
	('Boleta para primera ronda', 2, 136),
	('Boleta para primera ronda', 3, 136),
	('Boleta para primera ronda', 4, 136),
	('Boleta para primera ronda', 5, 136),
	('Boleta para primera ronda', 1, 137),
	('Boleta para primera ronda', 2, 137),
	('Boleta para primera ronda', 3, 137),
	('Boleta para primera ronda', 4, 137),
	('Boleta para primera ronda', 5, 137),
	('Boleta para primera ronda', 1, 138),
	('Boleta para primera ronda', 2, 138),
	('Boleta para primera ronda', 3, 138),
	('Boleta para primera ronda', 4, 138),
	('Boleta para primera ronda', 5, 138),
	('Boleta para primera ronda', 1, 139),
	('Boleta para primera ronda', 2, 139),
	('Boleta para primera ronda', 3, 139),
	('Boleta para primera ronda', 4, 139),
	('Boleta para primera ronda', 5, 139),
	('Boleta para primera ronda', 1, 155),
	('Boleta para primera ronda', 2, 155),
	('Boleta para primera ronda', 3, 155),
	('Boleta para primera ronda', 4, 155),
	('Boleta para primera ronda', 5, 155),
	('Boleta para primera ronda', 1, 156),
	('Boleta para primera ronda', 2, 156),
	('Boleta para primera ronda', 3, 156),
	('Boleta para primera ronda', 4, 156),
	('Boleta para primera ronda', 5, 156),
	('Boleta para primera ronda', 1, 157),
	('Boleta para primera ronda', 2, 157),
	('Boleta para primera ronda', 3, 157),
	('Boleta para primera ronda', 4, 157),
	('Boleta para primera ronda', 5, 157),
	('Boleta para primera ronda', 1, 158),
	('Boleta para primera ronda', 2, 158),
	('Boleta para primera ronda', 3, 158),
	('Boleta para primera ronda', 4, 158),
	('Boleta para primera ronda', 5, 158),
	('Boleta para primera ronda', 1, 159),
	('Boleta para primera ronda', 2, 159),
	('Boleta para primera ronda', 3, 159),
	('Boleta para primera ronda', 4, 159),
	('Boleta para primera ronda', 5, 159),
	('Boleta para primera ronda', 1, 160),
	('Boleta para primera ronda', 2, 160),
	('Boleta para primera ronda', 3, 160),
	('Boleta para primera ronda', 4, 160),
	('Boleta para primera ronda', 5, 160),
	('Boleta para primera ronda', 1, 161),
	('Boleta para primera ronda', 2, 161),
	('Boleta para primera ronda', 3, 161),
	('Boleta para primera ronda', 4, 161),
	('Boleta para primera ronda', 5, 161),
	('Boleta para primera ronda', 1, 162),
	('Boleta para primera ronda', 2, 162),
	('Boleta para primera ronda', 3, 162),
	('Boleta para primera ronda', 4, 162),
	('Boleta para primera ronda', 5, 162),
	('Boleta para primera ronda', 1, 170),
	('Boleta para primera ronda', 2, 170),
	('Boleta para primera ronda', 3, 170),
	('Boleta para primera ronda', 4, 170),
	('Boleta para primera ronda', 5, 170),
	('Boleta para primera ronda', 1, 171),
	('Boleta para primera ronda', 2, 171),
	('Boleta para primera ronda', 3, 171),
	('Boleta para primera ronda', 4, 171),
	('Boleta para primera ronda', 5, 171),
	('Boleta para primera ronda', 1, 172),
	('Boleta para primera ronda', 2, 172),
	('Boleta para primera ronda', 3, 172),
	('Boleta para primera ronda', 4, 172),
	('Boleta para primera ronda', 5, 172),
	('Boleta para primera ronda', 1, 173),
	('Boleta para primera ronda', 2, 173),
	('Boleta para primera ronda', 3, 173),
	('Boleta para primera ronda', 4, 173),
	('Boleta para primera ronda', 5, 173),
	('Boleta para primera ronda', 1, 174),
	('Boleta para primera ronda', 2, 174),
	('Boleta para primera ronda', 3, 174),
	('Boleta para primera ronda', 4, 174),
	('Boleta para primera ronda', 5, 174),
	('Boleta para primera ronda', 1, 175),
	('Boleta para primera ronda', 2, 175),
	('Boleta para primera ronda', 3, 175),
	('Boleta para primera ronda', 4, 175),
	('Boleta para primera ronda', 5, 175),
	('Boleta para primera ronda', 1, 176),
	('Boleta para primera ronda', 2, 176),
	('Boleta para primera ronda', 3, 176),
	('Boleta para primera ronda', 4, 176),
	('Boleta para primera ronda', 5, 176),
	('Boleta para primera ronda', 1, 177),
	('Boleta para primera ronda', 2, 177),
	('Boleta para primera ronda', 3, 177),
	('Boleta para primera ronda', 4, 177),
	('Boleta para primera ronda', 5, 177),
	('Boleta para segunda ronda', 1, 17),
	('Boleta para segunda ronda', 2, 17),
	('Boleta para segunda ronda', 3, 17),
	('Boleta para segunda ronda', 4, 17),
	('Boleta para segunda ronda', 5, 17),
	('Boleta para segunda ronda', 1, 18),
	('Boleta para segunda ronda', 2, 18),
	('Boleta para segunda ronda', 3, 18),
	('Boleta para segunda ronda', 4, 18),
	('Boleta para segunda ronda', 5, 18),
	('Boleta para segunda ronda', 1, 19),
	('Boleta para segunda ronda', 2, 19),
	('Boleta para segunda ronda', 3, 19),
	('Boleta para segunda ronda', 4, 19),
	('Boleta para segunda ronda', 5, 19),
	('Boleta para segunda ronda', 1, 20),
	('Boleta para segunda ronda', 2, 20),
	('Boleta para segunda ronda', 3, 20),
	('Boleta para segunda ronda', 4, 20),
	('Boleta para segunda ronda', 5, 20),
	('Boleta para segunda ronda', 1, 21),
	('Boleta para segunda ronda', 2, 21),
	('Boleta para segunda ronda', 3, 21),
	('Boleta para segunda ronda', 4, 21),
	('Boleta para segunda ronda', 5, 21),
	('Boleta para segunda ronda', 1, 22),
	('Boleta para segunda ronda', 2, 22),
	('Boleta para segunda ronda', 3, 22),
	('Boleta para segunda ronda', 4, 22),
	('Boleta para segunda ronda', 5, 22),
	('Boleta para segunda ronda', 1, 23),
	('Boleta para segunda ronda', 2, 23),
	('Boleta para segunda ronda', 3, 23),
	('Boleta para segunda ronda', 4, 23),
	('Boleta para segunda ronda', 5, 23),
	('Boleta para segunda ronda', 1, 24),
	('Boleta para segunda ronda', 2, 24),
	('Boleta para segunda ronda', 3, 24),
	('Boleta para segunda ronda', 4, 24),
	('Boleta para segunda ronda', 5, 24),
	('Boleta para segunda ronda', 1, 63),
	('Boleta para segunda ronda', 2, 63),
	('Boleta para segunda ronda', 3, 63),
	('Boleta para segunda ronda', 4, 63),
	('Boleta para segunda ronda', 5, 63),
	('Boleta para segunda ronda', 1, 64),
	('Boleta para segunda ronda', 2, 64),
	('Boleta para segunda ronda', 3, 64),
	('Boleta para segunda ronda', 4, 64),
	('Boleta para segunda ronda', 5, 64),
	('Boleta para segunda ronda', 1, 65),
	('Boleta para segunda ronda', 2, 65),
	('Boleta para segunda ronda', 3, 65),
	('Boleta para segunda ronda', 4, 65),
	('Boleta para segunda ronda', 5, 65),
	('Boleta para segunda ronda', 1, 66),
	('Boleta para segunda ronda', 2, 66),
	('Boleta para segunda ronda', 3, 66),
	('Boleta para segunda ronda', 4, 66),
	('Boleta para segunda ronda', 5, 66),
	('Boleta para segunda ronda', 1, 67),
	('Boleta para segunda ronda', 2, 67),
	('Boleta para segunda ronda', 3, 67),
	('Boleta para segunda ronda', 4, 67),
	('Boleta para segunda ronda', 5, 67),
	('Boleta para segunda ronda', 1, 68),
	('Boleta para segunda ronda', 2, 68),
	('Boleta para segunda ronda', 3, 68),
	('Boleta para segunda ronda', 4, 68),
	('Boleta para segunda ronda', 5, 68),
	('Boleta para segunda ronda', 1, 69),
	('Boleta para segunda ronda', 2, 69),
	('Boleta para segunda ronda', 3, 69),
	('Boleta para segunda ronda', 4, 69),
	('Boleta para segunda ronda', 5, 69),
	('Boleta para segunda ronda', 1, 70),
	('Boleta para segunda ronda', 2, 70),
	('Boleta para segunda ronda', 3, 70),
	('Boleta para segunda ronda', 4, 70),
	('Boleta para segunda ronda', 5, 70),
	('Boleta para segunda ronda', 1, 109),
	('Boleta para segunda ronda', 2, 109),
	('Boleta para segunda ronda', 3, 109),
	('Boleta para segunda ronda', 4, 109),
	('Boleta para segunda ronda', 5, 109),
	('Boleta para segunda ronda', 1, 110),
	('Boleta para segunda ronda', 2, 110),
	('Boleta para segunda ronda', 3, 110),
	('Boleta para segunda ronda', 4, 110),
	('Boleta para segunda ronda', 5, 110),
	('Boleta para segunda ronda', 1, 111),
	('Boleta para segunda ronda', 2, 111),
	('Boleta para segunda ronda', 3, 111),
	('Boleta para segunda ronda', 4, 111),
	('Boleta para segunda ronda', 5, 111),
	('Boleta para segunda ronda', 1, 112),
	('Boleta para segunda ronda', 2, 112),
	('Boleta para segunda ronda', 3, 112),
	('Boleta para segunda ronda', 4, 112),
	('Boleta para segunda ronda', 5, 112),
	('Boleta para segunda ronda', 1, 113),
	('Boleta para segunda ronda', 2, 113),
	('Boleta para segunda ronda', 3, 113),
	('Boleta para segunda ronda', 4, 113),
	('Boleta para segunda ronda', 5, 113),
	('Boleta para segunda ronda', 1, 114),
	('Boleta para segunda ronda', 2, 114),
	('Boleta para segunda ronda', 3, 114),
	('Boleta para segunda ronda', 4, 114),
	('Boleta para segunda ronda', 5, 114),
	('Boleta para segunda ronda', 1, 115),
	('Boleta para segunda ronda', 2, 115),
	('Boleta para segunda ronda', 3, 115),
	('Boleta para segunda ronda', 4, 115),
	('Boleta para segunda ronda', 5, 115),
	('Boleta para segunda ronda', 1, 116),
	('Boleta para segunda ronda', 2, 116),
	('Boleta para segunda ronda', 3, 116),
	('Boleta para segunda ronda', 4, 116),
	('Boleta para segunda ronda', 5, 116),
	('Boleta para segunda ronda', 1, 140),
	('Boleta para segunda ronda', 2, 140),
	('Boleta para segunda ronda', 3, 140),
	('Boleta para segunda ronda', 4, 140),
	('Boleta para segunda ronda', 5, 140),
	('Boleta para segunda ronda', 1, 141),
	('Boleta para segunda ronda', 2, 141),
	('Boleta para segunda ronda', 3, 141),
	('Boleta para segunda ronda', 4, 141),
	('Boleta para segunda ronda', 5, 141),
	('Boleta para segunda ronda', 1, 142),
	('Boleta para segunda ronda', 2, 142),
	('Boleta para segunda ronda', 3, 142),
	('Boleta para segunda ronda', 4, 142),
	('Boleta para segunda ronda', 5, 142),
	('Boleta para segunda ronda', 1, 143),
	('Boleta para segunda ronda', 2, 143),
	('Boleta para segunda ronda', 3, 143),
	('Boleta para segunda ronda', 4, 143),
	('Boleta para segunda ronda', 5, 143),
	('Boleta para segunda ronda', 1, 144),
	('Boleta para segunda ronda', 2, 144),
	('Boleta para segunda ronda', 3, 144),
	('Boleta para segunda ronda', 4, 144),
	('Boleta para segunda ronda', 5, 144),
	('Boleta para segunda ronda', 1, 145),
	('Boleta para segunda ronda', 2, 145),
	('Boleta para segunda ronda', 3, 145),
	('Boleta para segunda ronda', 4, 145),
	('Boleta para segunda ronda', 5, 145),
	('Boleta para segunda ronda', 1, 146),
	('Boleta para segunda ronda', 2, 146),
	('Boleta para segunda ronda', 3, 146),
	('Boleta para segunda ronda', 4, 146),
	('Boleta para segunda ronda', 5, 146),
	('Boleta para segunda ronda', 1, 147),
	('Boleta para segunda ronda', 2, 147),
	('Boleta para segunda ronda', 3, 147),
	('Boleta para segunda ronda', 4, 147),
	('Boleta para segunda ronda', 5, 147),
	('Boleta para cuartos, 1, 25),
	('Boleta para cuartos, 2, 25),
	('Boleta para cuartos, 3, 25),
	('Boleta para cuartos, 4, 25),
	('Boleta para cuartos, 5, 25),
	('Boleta para cuartos, 1, 26),
	('Boleta para cuartos, 2, 26),
	('Boleta para cuartos, 3, 26),
	('Boleta para cuartos, 4, 26),
	('Boleta para cuartos, 5, 26),
	('Boleta para cuartos, 1, 27),
	('Boleta para cuartos, 2, 27),
	('Boleta para cuartos, 3, 27),
	('Boleta para cuartos, 4, 27),
	('Boleta para cuartos, 5, 27),
	('Boleta para cuartos, 1, 28),
	('Boleta para cuartos, 2, 28),
	('Boleta para cuartos, 3, 28),
	('Boleta para cuartos, 4, 28),
	('Boleta para cuartos, 5, 28),
	('Boleta para cuartos, 1, 40),
	('Boleta para cuartos, 2, 40),
	('Boleta para cuartos, 3, 40),
	('Boleta para cuartos, 4, 40),
	('Boleta para cuartos, 5, 40),
	('Boleta para cuartos, 1, 41),
	('Boleta para cuartos, 2, 41),
	('Boleta para cuartos, 3, 41),
	('Boleta para cuartos, 4, 41),
	('Boleta para cuartos, 5, 41),
	('Boleta para cuartos, 1, 42),
	('Boleta para cuartos, 2, 42),
	('Boleta para cuartos, 3, 42),
	('Boleta para cuartos, 4, 42),
	('Boleta para cuartos, 5, 42),
	('Boleta para cuartos, 1, 43),
	('Boleta para cuartos, 2, 43),
	('Boleta para cuartos, 3, 43),
	('Boleta para cuartos, 4, 43),
	('Boleta para cuartos, 5, 43),
	('Boleta para cuartos, 1, 71),
	('Boleta para cuartos, 2, 71),
	('Boleta para cuartos, 3, 71),
	('Boleta para cuartos, 4, 71),
	('Boleta para cuartos, 5, 71),
	('Boleta para cuartos, 1, 72),
	('Boleta para cuartos, 2, 72),
	('Boleta para cuartos, 3, 72),
	('Boleta para cuartos, 4, 72),
	('Boleta para cuartos, 5, 72),
	('Boleta para cuartos, 1, 73),
	('Boleta para cuartos, 2, 73),
	('Boleta para cuartos, 3, 73),
	('Boleta para cuartos, 4, 73),
	('Boleta para cuartos, 5, 73),
	('Boleta para cuartos, 1, 74),
	('Boleta para cuartos, 2, 74),
	('Boleta para cuartos, 3, 74),
	('Boleta para cuartos, 4, 74),
	('Boleta para cuartos, 5, 74),
	('Boleta para cuartos, 1, 86),
	('Boleta para cuartos, 2, 86),
	('Boleta para cuartos, 3, 86),
	('Boleta para cuartos, 4, 86),
	('Boleta para cuartos, 5, 86),
	('Boleta para cuartos, 1, 87),
	('Boleta para cuartos, 2, 87),
	('Boleta para cuartos, 3, 87),
	('Boleta para cuartos, 4, 87),
	('Boleta para cuartos, 5, 87),
	('Boleta para cuartos, 1, 88),
	('Boleta para cuartos, 2, 88),
	('Boleta para cuartos, 3, 88),
	('Boleta para cuartos, 4, 88),
	('Boleta para cuartos, 5, 88),
	('Boleta para cuartos, 1, 89),
	('Boleta para cuartos, 2, 89),
	('Boleta para cuartos, 3, 89),
	('Boleta para cuartos, 4, 89),
	('Boleta para cuartos, 5, 89),
	('Boleta para cuartos, 1, 117),
	('Boleta para cuartos, 2, 117),
	('Boleta para cuartos, 3, 117),
	('Boleta para cuartos, 4, 117),
	('Boleta para cuartos, 5, 117),
	('Boleta para cuartos, 1, 118),
	('Boleta para cuartos, 2, 118),
	('Boleta para cuartos, 3, 118),
	('Boleta para cuartos, 4, 118),
	('Boleta para cuartos, 5, 118),
	('Boleta para cuartos, 1, 119),
	('Boleta para cuartos, 2, 119),
	('Boleta para cuartos, 3, 119),
	('Boleta para cuartos, 4, 119),
	('Boleta para cuartos, 5, 119),
	('Boleta para cuartos, 1, 120),
	('Boleta para cuartos, 2, 120),
	('Boleta para cuartos, 3, 120),
	('Boleta para cuartos, 4, 120),
	('Boleta para cuartos, 5, 120),
	('Boleta para cuartos, 1, 148),
	('Boleta para cuartos, 2, 148),
	('Boleta para cuartos, 3, 148),
	('Boleta para cuartos, 4, 148),
	('Boleta para cuartos, 5, 148),
	('Boleta para cuartos, 1, 149),
	('Boleta para cuartos, 2, 149),
	('Boleta para cuartos, 3, 149),
	('Boleta para cuartos, 4, 149),
	('Boleta para cuartos, 5, 149),
	('Boleta para cuartos, 1, 150),
	('Boleta para cuartos, 2, 150),
	('Boleta para cuartos, 3, 150),
	('Boleta para cuartos, 4, 150),
	('Boleta para cuartos, 5, 150),
	('Boleta para cuartos, 1, 151),
	('Boleta para cuartos, 2, 151),
	('Boleta para cuartos, 3, 151),
	('Boleta para cuartos, 4, 151),
	('Boleta para cuartos, 5, 151),
	('Boleta para cuartos, 1, 163),
	('Boleta para cuartos, 2, 163),
	('Boleta para cuartos, 3, 163),
	('Boleta para cuartos, 4, 163),
	('Boleta para cuartos, 5, 163),
	('Boleta para cuartos, 1, 164),
	('Boleta para cuartos, 2, 164),
	('Boleta para cuartos, 3, 164),
	('Boleta para cuartos, 4, 164),
	('Boleta para cuartos, 5, 164),
	('Boleta para cuartos, 1, 165),
	('Boleta para cuartos, 2, 165),
	('Boleta para cuartos, 3, 165),
	('Boleta para cuartos, 4, 165),
	('Boleta para cuartos, 5, 165),
	('Boleta para cuartos, 1, 166),
	('Boleta para cuartos, 2, 166),
	('Boleta para cuartos, 3, 166),
	('Boleta para cuartos, 4, 166),
	('Boleta para cuartos, 5, 166),
	('Boleta para cuartos, 1, 178),
	('Boleta para cuartos, 2, 178),
	('Boleta para cuartos, 3, 178),
	('Boleta para cuartos, 4, 178),
	('Boleta para cuartos, 5, 178),
	('Boleta para cuartos, 1, 179),
	('Boleta para cuartos, 2, 179),
	('Boleta para cuartos, 3, 179),
	('Boleta para cuartos, 4, 179),
	('Boleta para cuartos, 5, 179),
	('Boleta para cuartos, 1, 180),
	('Boleta para cuartos, 2, 180),
	('Boleta para cuartos, 3, 180),
	('Boleta para cuartos, 4, 180),
	('Boleta para cuartos, 5, 180),
	('Boleta para cuartos, 1, 181),
	('Boleta para cuartos, 2, 181),
	('Boleta para cuartos, 3, 181),
	('Boleta para cuartos, 4, 181),
	('Boleta para cuartos, 5, 181),
	('Boleta para semi, 1, 29),
	('Boleta para semi, 2, 29),
	('Boleta para semi, 3, 29),
	('Boleta para semi, 4, 29),
	('Boleta para semi, 5, 29),
	('Boleta para semi, 1, 30),
	('Boleta para semi, 2, 30),
	('Boleta para semi, 3, 30),
	('Boleta para semi, 4, 30),
	('Boleta para semi, 5, 30),
	('Boleta para semi, 1, 44),
	('Boleta para semi, 2, 44),
	('Boleta para semi, 3, 44),
	('Boleta para semi, 4, 44),
	('Boleta para semi, 5, 44),
	('Boleta para semi, 1, 45),
	('Boleta para semi, 2, 45),
	('Boleta para semi, 3, 45),
	('Boleta para semi, 4, 45),
	('Boleta para semi, 5, 45),
	('Boleta para semi, 1, 75),
	('Boleta para semi, 2, 75),
	('Boleta para semi, 3, 75),
	('Boleta para semi, 4, 75),
	('Boleta para semi, 5, 75),
	('Boleta para semi, 1, 76),
	('Boleta para semi, 2, 76),
	('Boleta para semi, 3, 76),
	('Boleta para semi, 4, 76),
	('Boleta para semi, 5, 76),
	('Boleta para semi, 1, 90),
	('Boleta para semi, 2, 90),
	('Boleta para semi, 3, 90),
	('Boleta para semi, 4, 90),
	('Boleta para semi, 5, 90),
	('Boleta para semi, 1, 91),
	('Boleta para semi, 2, 91),
	('Boleta para semi, 3, 91),
	('Boleta para semi, 4, 91),
	('Boleta para semi, 5, 91),
	('Boleta para semi, 1, 121),
	('Boleta para semi, 2, 121),
	('Boleta para semi, 3, 121),
	('Boleta para semi, 4, 121),
	('Boleta para semi, 5, 121),
	('Boleta para semi, 1, 122),
	('Boleta para semi, 2, 122),
	('Boleta para semi, 3, 122),
	('Boleta para semi, 4, 122),
	('Boleta para semi, 5, 122),
	('Boleta para semi, 1, 152),
	('Boleta para semi, 2, 152),
	('Boleta para semi, 3, 152),
	('Boleta para semi, 4, 152),
	('Boleta para semi, 5, 152),
	('Boleta para semi, 1, 153),
	('Boleta para semi, 2, 153),
	('Boleta para semi, 3, 153),
	('Boleta para semi, 4, 153),
	('Boleta para semi, 5, 153),
	('Boleta para semi, 1, 167),
	('Boleta para semi, 2, 167),
	('Boleta para semi, 3, 167),
	('Boleta para semi, 4, 167),
	('Boleta para semi, 5, 167),
	('Boleta para semi, 1, 168),
	('Boleta para semi, 2, 168),
	('Boleta para semi, 3, 168),
	('Boleta para semi, 4, 168),
	('Boleta para semi, 5, 168),
	('Boleta para semi, 1, 182),
	('Boleta para semi, 2, 182),
	('Boleta para semi, 3, 182),
	('Boleta para semi, 4, 182),
	('Boleta para semi, 5, 182),
	('Boleta para semi, 1, 183),
	('Boleta para semi, 2, 183),
	('Boleta para semi, 3, 183),
	('Boleta para semi, 4, 183),
	('Boleta para semi, 5, 183),
	('Boleta para final, 1, 31),
	('Boleta para final, 2, 31),
	('Boleta para final, 3, 31),
	('Boleta para final, 4, 31),
	('Boleta para final, 5, 31),
	('Boleta para final, 1, 46),
	('Boleta para final, 2, 46),
	('Boleta para final, 3, 46),
	('Boleta para final, 4, 46),
	('Boleta para final, 5, 46),
	('Boleta para final, 1, 77),
	('Boleta para final, 2, 77),
	('Boleta para final, 3, 77),
	('Boleta para final, 4, 77),
	('Boleta para final, 5, 77),
	('Boleta para final, 1, 92),
	('Boleta para final, 2, 92),
	('Boleta para final, 3, 92),
	('Boleta para final, 4, 92),
	('Boleta para final, 5, 92),
	('Boleta para final, 1, 123),
	('Boleta para final, 2, 123),
	('Boleta para final, 3, 123),
	('Boleta para final, 4, 123),
	('Boleta para final, 5, 123),
	('Boleta para final, 1, 154),
	('Boleta para final, 2, 154),
	('Boleta para final, 3, 154),
	('Boleta para final, 4, 154),
	('Boleta para final, 5, 154),
	('Boleta para final, 1, 169),
	('Boleta para final, 2, 169),
	('Boleta para final, 3, 169),
	('Boleta para final, 4, 169),
	('Boleta para final, 5, 169),
	('Boleta para final, 1, 184),
	('Boleta para final, 2, 184),
	('Boleta para final, 3, 184),
	('Boleta para final, 4, 184),
	('Boleta para final, 5, 184);