INSERT INTO ciudades (nombre, id_pais) VALUES 
    ('El Palmar', 1),
    ('Belgrade', 2),
    ('Moscow', 3),
    ('Oslo', 4),
    ('Athens', 5),
    ('Gentofte', 6),
    ('San Candido', 7),
    ('Rancho Santa Fe', 8),
    ('Montreal', 9),
    ('Hyattsville', 8),
    ('Wrocław', 10),
    ('Johannesburg', 11),
    ('Hamburg', 12),
    ('Carrara', 7),
    ('Voorhees Township', 8),
    ('Sydney', 13),
    ('Castellón de la Plana', 1),
    ('Haskovo', 14),
    ('Zagreb', 15),
    ('Tel Aviv', 16),
    ('Buenos Aires', 17),
    ('Bradenton', 8),
    ('Tsu', 18),
    ('Birmingham', 19),
    ('Atlanta', 8),
    ('Liège', 20),
    ('Paris', 21),
    ('Metz', 21),
    ('Santiago', 22),
    ('Greensboro', 8),
    ('Medjugorje', 23),
    ('Wageningen', 24),
    ('Barcelona', 1),
    ('Sanremo', 7),
    ('Mladá Boleslav', 36),
    ('Soisy-sous-Montmorency', 21),
    ('Béziers', 21),
    ('Sutton', 19),
    ('Turin', 7),
    ('Piedmont', 8),
    ('Sombor', 2),
    ('Bell Ville', 17),
    ('San Diego', 8),
    ('Gatchina', 3),
    ('Warstein', 12),
    ('Haarlem', 24),
    ('Helsinki', 25),
    ('Zürich', 26),
    ('Nîmes', 21),
    ('Santanyí', 1),
    ('Nyíregyháza', 27),
    ('Senta', 2),
    ('Vladikavkaz', 3),
    ('Maia', 32),
    ('Fortaleza', 28),
    ('Valencia', 1),
    ('Palermo', 7),
    ('Kempen', 12),
    ('Neuilly-sur-Seine', 21),
    ('Riyadh', 29),
    ('Kiev', 30),
    ('Gijon', 1),
    ('Skara', 31),
    ('Rincón de la Victoria', 1),
    ('Guimarães', 32),
    ('Chisinau', 33),
    ('Hangzhou', 34),
    ('Brisbane', 13),
    ('Rosario', 17),
    ('Marechal Cândido Rondon', 28),
    ('Furtwangen', 12),
    ('Presov', 36),
    ('Ascoli Piceno', 7),
    ('Trinidad', 35),
    ('Cologne', 12),
    ('Pesaro', 7),
    ('Beroun', 36),
    ('Karlsruhe', 12),
    ('Amiens', 21),
    ('Perugia', 7),
    ('Florence', 7),
    ('Rostov-on-Don', 3),
    ('Novi Pazar', 2),
    ('Burgos', 1),
    ('Beijing', 34),
    ('Lohja', 25),
    ('Split', 15),
    ('Lima', 37),
    ('Budapest', 27),
    ('Kremenchuk', 30),
    ('Tenerife', 1),
    ('Cuenca', 1),
    ('Montbrison', 21),
    ('Nuremberg', 12),
    ('Saint-Malo', 21),
    ('Bondoufle', 21),
    ('Villa Gesell', 17),
    ('Riga', 38),
    ('Coral Springs', 8),
    ('Nice', 21),
    ('Campinas', 28),
    ('Bucaramanga', 39),
    ('La Plata', 17),
    ('Charenton-le-Pont', 21),
    ('Toulouse', 21),
    ('Grande-Synthe', 21),
    ('Galanta', 36);

SELECT * FROM ciudades;
