INSERT INTO entidades_de_trasmision (nombre, id_area_geografica) VALUES
('France TV', 1),
('Prime Video', 1),
('Eurosport', 2), 
('Servus TV', 3), 
('RTBF', 4), 
('SRG SSR', 5), 
('NBC Sports', 6), 
('Peacock', 6), 
('Tennis Channel', 6),
('Bally Sports', 6), 
('TSN', 7), 
('RDS', 7), 
('Star+', 8), 
('ESPN Brasil', 9), 
('beIN Sports', 10), 
('SuperSport', 11), 
('Canal+', 11), 
('CCTV', 13), 
('Elta TV', 14), 
('VTVcab', 15), 
('Wowow', 16), 
('SonySports', 17), 
('Premier Sports', 18), 
('Nine World of Sports', 19), 
('Sky', 20), 
('CJ ENM', 21); 

SELECT * FROM entidades_de_trasmision;