INSERT INTO paises (nombre) VALUES 
    ('España'),
    ('Serbia'),
    ('Rusia'),
    ('Noruega'),
    ('Grecia'),
    ('Dinamarca'),
    ('Italia'),
    ('Estados Unidos'),
    ('Canadá'),
    ('Polonia'),
    ('Sudáfrica'),
    ('Alemania'),
    ('Australia'),
    ('Bulgaria'),
    ('Croacia'),
    ('Israel'),
    ('Argentina'),
    ('Japón'),
    ('Inglaterra'),
    ('Bélgica'),
    ('Francia'),
    ('Chile'),
    ('Bosnia y Herzegovina'),
    ('Países Bajos'),
    ('Finlandia'),
    ('Suiza'),
    ('Hungría'),
    ('Brasil'),
    ('Arabia Saudita'),
    ('Ucrania'),
    ('Suecia'),
    ('Portugal'),
    ('Moldavia'),
    ('China'),
    ('Bolivia'),
    ('Eslovaquia'),
    ('Perú'),
    ('Letonia'),
    ('Colombia'),
	('Bielorrusia'),
	('Túnez'),
	('Grecia'),
	('República Checa'),
	('Rumania'),
	('Egipto'),
	('Estonia');

SELECT * FROM paises;